package org.example.Logic;

import org.example.Data.Mailtype;

import java.util.ArrayList;
import java.util.List;

public class PostOffice {
    private List<Mail> mails;

    public PostOffice() {
        this.mails = new ArrayList<>();
    }

    public void addToMails(Mail mail) {
        mails.add(mail);
    }

    public void listAllMailOnGivenDate(String date) { //stream??
        System.out.println("Mails posted on " + date + ": ");
        for (Mail mail : mails) {
            if (mail.getDate().toString().equals(date)) {
                System.out.println(mail);
            }
        }
    }

    public double getRevenueForType(Mailtype type) { //stream??
        double sum = 0;
        for (Mail mail : mails) {
            if (mail.getType() == type) {
                System.out.println(mail);
                sum += mail.getPrice();
            }
        }
        System.out.println("Revenue generated by " + type + " type: " + sum);
        return sum;
    }
}
